package com.api.Model;

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Email;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.springframework.data.annotation.LastModifiedDate;

import io.swagger.annotations.ApiModelProperty;




@Entity
@Table(name="emplyeesss")
public class Employee {
	
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@ApiModelProperty(value = "autogenerated id")
	private int id;

	 @NotNull(message="Name must fill")
	 @Size(min = 2, message = "First Name should have atleast 2 characters")
	 @ApiModelProperty(value = "Employee Name")
	private String name;
	 
	 @Size(min = 2, message = "age should have atleast 2 characters")
	 @NotNull(message="age must fill")
	 @ApiModelProperty(value = "Employee age")
	private String age;
	 
	 @Email
	 @NotNull(message="emil must fill")
	 @ApiModelProperty(value = "Employee Email")
	private String email;
	 
	// @Size(min = 2, message = "First Name should have atleast 2 characters")
	 @NotNull(message="DOB must fill")
	 @ApiModelProperty(value = "Employee DOB")
	private String DOB;
	 
	 @Size(min = 2, message = "campany Name should have atleast 2 characters")
	 @NotNull(message="CompanyName must fill")
	 @ApiModelProperty(value = "Employee companyLocation")
	private String companyName;
	 
	 @Size(min = 2, message = "companylocation  should have atleast 2 characters")
	 @NotNull(message="CompanyLocation must fill")
	 @ApiModelProperty(value = "Employee companyLocation")
	private String companyLocation;
	 
	 @Size(min = 2, message = "address  should have atleast 2 characters")
	 @NotNull(message="address must fill")
	 @ApiModelProperty(value = "Employee address")
	private String address;
	 
	 @Size(min = 2, message = "First Name should have atleast 2 characters")
	 @NotNull(message="designation must fill")
	 @ApiModelProperty(value = "Employee designation")
	private String designation;
	 
	 @Size(min = 2, message = "experice should have atleast 2 characters")
	 @NotNull(message="experience must fill")
	 @ApiModelProperty(value = "Employee experice")
	private String experience;
	 
	 @Size(min = 7, message = "First Name should have atleast 2 characters")
	 @NotNull(message="phoneno must fill")
	 @ApiModelProperty(value = "Employee phoneNo")
	private String phoneno;
	 
	 @Size(min = 2, message = "salary  should have atleast 2 characters")
	 @NotNull(message="salary must fill")
	 @ApiModelProperty(value = "Employee salary")
	private String salary;
	
	@Temporal(TemporalType.TIMESTAMP)
	@LastModifiedDate
	private Date createdAt;
	
	//setter and getter method

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getDOB() {
		return DOB;
	}

	public void setDOB(String dOB) {
		DOB = dOB;
	}

	public String getCompanyName() {
		return companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public String getCompanyLocation() {
		return companyLocation;
	}

	public void setCompanyLocation(String companyLocation) {
		this.companyLocation = companyLocation;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getDesignation() {
		return designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	public String getExperience() {
		return experience;
	}

	public void setExperience(String experience) {
		this.experience = experience;
	}

	public String getPhoneno() {
		return phoneno;
	}

	public void setPhoneno(String phoneno) {
		this.phoneno = phoneno;
	}

	public String getSalary() {
		return salary;
	}

	public void setSalary(String salary) {
		this.salary = salary;
	}

	public Date getCreatedAt() {
		return createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public String getAge() {
		return age;
	}

	public void setAge(String age) {
		this.age = age;
	}

	public Employee() {
		
	}
	
	public Employee(int id, String name, String age, String email, String DOB, String companyName,
			String companyLocation, String address, String designation, String experience, String phoneno,
			String salary, Date createdAt) {
		
		this.id = id;
		this.name = name;
		this.age = age;
		this.email = email;
		this.DOB = DOB;
		this.companyName = companyName;
		this.companyLocation = companyLocation;
		this.address = address;
		this.designation = designation;
		this.experience = experience;
		this.phoneno = phoneno;
		this.salary = salary;
		this.createdAt = createdAt;
	}
	
	
	
	


}
